---
root: true

env:
  browser: true
  node: true
  es2021 : true

extends:
  - "airbnb-base"

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  no-unused-vars: 0
  max-len: ["error", { "code": 150 }]
